// National ER directory (server-side). Loads the geocoded CMS hospital list
// generated by src/build-national-directory.js and exposes a nearest-N lookup.
// ~4,400 hospitals — small enough to scan per request.
import data from './hospitals-national.json';
import { haversineMiles, type LatLng } from './geo';

export interface NationalHospital {
  id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  edv: string | null;
  edvOrdinal: number | null;
  op18b: number | null;
  op22: number | null;
  rating: number | null;
}

export const NATIONAL = data as NationalHospital[];

export interface NearbyHospital {
  hospital: NationalHospital;
  miles: number;
}

// Nearest `n` hospitals to an origin, closest first, with great-circle distance.
export function nearestHospitals(origin: LatLng, n: number): NearbyHospital[] {
  const scored = NATIONAL.map((h) => ({
    hospital: h,
    miles: haversineMiles(origin, { lat: h.lat, lng: h.lng }),
  }));
  scored.sort((a, b) => a.miles - b.miles);
  return scored.slice(0, n);
}

// A compact, readable label from a long CMS facility name.
const STRIP = /\b(hospital|hospitals|medical center|med ctr|center|health(care)?|system|regional|memorial|community|county|district|university|the|of|incorporated|inc|llc)\b/gi;
export function shortName(name: string): string {
  let s = name.replace(STRIP, ' ').replace(/[-–—]/g, ' ').replace(/\s+/g, ' ').trim();
  if (s.length < 3) s = name.replace(/\s+/g, ' ').trim();
  return s.length > 26 ? s.slice(0, 25).trim() + '…' : s;
}

// Rough San Francisco proximity test, used to gate SF-specific incident copy.
export function isNearSF(p: LatLng): boolean {
  return Math.abs(p.lat - 37.7749) < 0.5 && Math.abs(p.lng + 122.4194) < 0.6;
}
